install:
  - choco install gitversion.portable -pre -y
  - choco install gitlink -y
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))

assembly_info:
  patch: false

platform:
  - Any CPU

configuration:
  - Release

build_script:
  - cmd: nuget restore src\TestStack.White.sln
  - cmd: gitversion /l console /output buildserver /updateAssemblyInfo
  
  - cmd: msbuild src\TestStack.White.sln "/p:Configuration=%CONFIGURATION%;Platform=%PLATFORM%"

  - cmd: ECHO GitLink src\ -u https://github.com/TestStack/White -c %CONFIGURATION% -ignore WinformsTodo,WpfTodo,WpfTodo.UITests,Todo.Core,TestSilverlightApplication,TestSilverlightApplication.Web,WindowsFormsTestApplication,WinFormsTestApp.Old,WPFTestApp.Old,WpfTestApplication,TestStack.White.Reporting,TestStack.White.ScreenObjects,TestStack.White.ScreenObjects.UITests,TestStack.White.UITests,TestStack.White.UnitTests,TestStack.White.WebBrowser,TestStack.White.WebBrowser.UITests,TestStack.White.WebBrowser.UnitTests
  - cmd: GitLink . -u https://github.com/TestStack/White -c %CONFIGURATION% -ignore WinformsTodo,WpfTodo,WpfTodo.UITests,Todo.Core,TestSilverlightApplication,TestSilverlightApplication.Web,WindowsFormsTestApplication,WinFormsTestApp.Old,WPFTestApp.Old,WpfTestApplication,TestStack.White.Reporting,TestStack.White.ScreenObjects,TestStack.White.ScreenObjects.UITests,TestStack.White.UITests,TestStack.White.UnitTests,TestStack.White.WebBrowser,TestStack.White.WebBrowser.UITests,TestStack.White.WebBrowser.UnitTests

  - cmd: ECHO nuget pack nuget\TestStack.White.nuspec -version "%GitVersion_NuGetVersion%" -prop "configuration=%CONFIGURATION%"
  - cmd: nuget pack nuget\TestStack.White.nuspec -version "%GitVersion_NuGetVersion%" -prop "configuration=%CONFIGURATION%"

on_finish:
  - ps: if (Test-Path -path c:\FailedTestsScreenshots) { Get-ChildItem c:\FailedTestsScreenshots\*.* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }}

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified